---
- name: Prepare SDCARD
  hosts: local
  become: true
  become_user: root
  become_method: su
  tasks:
    - name: Pi tmp boot path directory exists
      ansible.builtin.file:
        path: "{{ tmp_pi_boot_path }}"
        owner: "{{ become_user }}"
        group: "{{ become_user }}"
        state: "{{ 'directory' if state == 'present' else state }}"

    - name: Pi4 boot packages are present
      ansible.builtin.dnf:
        name: "{{ pi4_boot_pkgs }}"
        releasever: "{{ fedora_release }}"
        state: "{{ present }}"
        update_cache: "{{ 'yes' if state == 'present' else 'no' }}"
        download_dir: "{{ tmp_rpm_dest_path }}"
        download_only: yes
        conf_file: "{{ playbook_dir }}/files/etc/dnf/dnf.conf"

    - name: Register list of rpms
      ansible.builtin.find:
        paths: "{{ tmp_rpm_dest_path }}"
        patterns:
          - "*rpm"
      register: rpms

    - name: Process RPMs to CPIO
      ansible.builtin.shell:
        cmd: rpm2cpio {{ item }} | cpio -idv -D {{ tmp_rpm_dest_path }}
      loop: rpms.files

    - name: Copy rpi4 u-boot.bin to temp boot dir
      ansible.builtin.copy:
        src: "{{ tmp_rpm_dest_path }}/usr/share/uboot/rpi_4/u-boot.bin"
        dest: "{{ tmp_pi_boot_path }}/rpi4-u-boot.bin"
      when: state == 'present'
...
