---
state: 'present'

ssh_user: "{{ ansible_user }}"
ssh_pub_key: "{{ lookup('file', /home/ssh_user/.ssh/id_rsa.pub) }}"

prereq_pkgs:
  - butane
  - coreos-installer
  - rpi-imager
    
worker_hostname: 'pi-worker-0'
master_hostname: 'pi-master-0'
...

